### ISSUE TITLE
JSON payload example / SSL verification 

### ISSUE THREAD

**Issue by df-5** [VisaDeveloperProgram/SampleCode#1]
In the [PHP example](https://github.com/VisaDeveloperProgram/SampleCode/blob/master/SampleCode/VisaAPICalls/PHP/CybersourceSample.php#L10), is the strange concatenation and everything being passed as a string (instead of something like an integer or float) intentional or is there a reason? Would something like this fail hashing?

```
$body = json_encode([
	'amount' => '0',
	'currency' => 'USD',
	'payment' => [
		'cardNumber' => '',
		'cardExpirationMonth' => '',
		'cardExpirationYear' => '',
	],
]);
```

Additionally, is there a specific bundle or certificates to use with an explicit `curl_setopt($ch, CURLOPT_CAINFO);`?

**Comment by VisaDeveloperProgram** [comment]
Hi,
Yup. We can definitely use the json_encode option you have specified. We agree that it is a cleaner approach than the concatenated string. It should not impact the hashing/token calculation. We will update this shortly in Git as well. Thanks for your feedback.

Around the other question on CURLOPT_CAINFO - Yes. The VDP platform certificate bundle is available for download in the "Certificate" section in the Application Details page in our [Portal] (https://developer.visa.com/)
<img width="1053" alt="screen shot 2016-02-06 at 12 13 52 pm" src="https://cloud.githubusercontent.com/assets/12734824/12865138/55c77d00-ccca-11e5-87f6-4f4ded8ff139.png">
