### ISSUE TITLE
Visa Checkout Button reurn json without callid

### ISSUE THREAD

**Issue by juhnowski** [VisaDeveloperProgram/SampleCode#11]
Hello. Excellent work, guys!

I made step by step tutorial from https://arch.developer.visa.com/vme/merchant/documents/Getting_Started_With_Visa_Checkout/Quick_Start_Tutorial.html

Class VisaCheckoutClient includes a constant:
private static String CALL_ID = "{put your call id here}";

Could you please clarify where I can find call id ? 
I got response without callid with following parameters:
encKey
encPaymentData
browserLocale
clientId
allowEnrollment
allowCustomBranding
allowEXO

Thank you.

**Comment by hemanthmanoharan** [comment]
@juhnowski The _callid_ is returned in the payload for the payment.success event. Please see the section 
**Response to Payment Success Events** in this [link](https://arch.developer.visa.com/vme/merchant/documents/Visa_Checkout_JavaScript_Integration_Guide/JavaScript_and_Button_Reference.html) for more details.

**Comment by juhnowski** [comment]
Dear Hemanthmanoharan, hello!

Thanks for a fast response.

The problem was in alert's message cutting of string. I have had an example code:

```
V.on("payment.success", function (payment)
                {
                    alert(JSON.stringify(payment));
```

and alert dialogs with cut-off message, but when I add to js code

`                    console.log(JSON.stringify(payment));`

full info about payment start showing in browser console :)
And I found _callid_.

Thank you. Your answer was very helpfull for me.

**Comment by VisaDeveloperProgram** [comment]
@juhnowski Good to know that your problem was resolved. Will close this issue then.
