### ISSUE TITLE
Insecure cryptographic construct for x-pay-token

### ISSUE THREAD

**Issue by eoftedal** [VisaDeveloperProgram/SampleCode#5]
The x-pay-token is generated using sha256(key||data). This construct is insecure as an attacker can add data to an existing signature. This is called a length extension attack. For a similar example see http://vnhacker.blogspot.no/2009/09/flickrs-api-signature-forgery.html?m=1 
 MD5 is used there, but you get the same problem with SHA256.

You should STRONGLY consider moving to HMAC-SHA256 instead.

**Comment by VisaDeveloperProgram** [comment]
Thanks for pointing out the same. We are fixing it in our immediate next release.

**Comment by VisaDeveloperProgram** [comment]
Visa Developer Platform has rolled out support for HMAC. The sample code has also been updated to reflect the same.
